# Generated by Django 5.1 on 2024-09-08 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_choice_votes_alter_question_pub_date_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 8, 12, 38, 4, 344600, tzinfo=datetime.timezone.utc)),
        ),
    ]
